import {FormEvent,useEffect,useRef,useState} from 'react';
import {Bot,CalendarDays,ChevronDown,HeartPulse,MapPin,MessageCircle,Send,Sparkles,X} from 'lucide-react';
import {useLocation,useNavigate} from 'react-router-dom';
import {useAuth} from '../context/AuthContext';
import {api} from '../services/api';

type Message={id:number;from:'assistant'|'user';text:string;actions?:string[]};
const greeting=(name='there',role='GUEST'):Message=>({id:Date.now(),from:'assistant',text:`Hello 👋 ${role==='DOCTOR'?'Dr. ':''}${name}\n\nI'm UHS AI Assistant. I'm here to help you with healthcare information, appointments, AI disease prediction, medical records, and navigation throughout the UHS platform.\n\nHow can I help you today?`,actions:['Book Appointment','Predict Disease','Find Doctor','Health Articles','BMI Calculator','Nearby Hospitals']});
const allActions=['Book Appointment','Predict Disease','Find Doctor','View Prescriptions','Medical Reports','Health Articles','Medicine Information','Diet Plans','Workout Plans','BMI Calculator','Nearby Hospitals','My Appointments','Contact Support'];
const symptoms=['fever','cough','headache','weak','fatigue','sore throat','nausea','body aches','shortness of breath'];
const emergencies=['chest pain','heart attack','stroke','breathing difficulty','severe bleeding','suicide','collapse'];
const protectedActions=new Set(['View Prescriptions','Medical Reports','My Appointments','Diet Plans','Workout Plans']);

function actionPath(action:string,role:string|undefined){
  if(action==='Book Appointment')return '/book'; if(action==='Predict Disease')return '/predict'; if(action==='Find Doctor')return '/doctors'; if(action==='Health Articles'||action==='Medicine Information')return '/library'; if(action==='Nearby Hospitals')return '/hospitals'; if(action==='Contact Support')return '/contact'; return `/dashboard/${role?.toLowerCase()??'patient'}`;
}
function finish(text:string,actions?:string[]):Message{return {id:Date.now(),from:'assistant',text:`${text}\n\nIs there anything else I can help you with?`,actions:actions??['Book Appointment','Predict Disease','Find Doctor','Health Articles']}}
function replyFor(input:string):Message{
  const q=input.toLowerCase().trim();
  if(emergencies.some(term=>q.includes(term)))return finish('This may be an emergency. Please call your local emergency service now or go to the nearest emergency department. Do not wait for an online response.',['Nearby Hospitals','Contact Support']);
  if(q.includes('bmi'))return finish('I can help calculate BMI. Send your height in cm and weight in kg, for example: “170 cm, 65 kg”.',['BMI Calculator']);
  const bmi=q.match(/(\d{2,3}(?:\.\d+)?)\s*(?:cm)?[^\d]+(\d{2,3}(?:\.\d+)?)\s*(?:kg)?/); if(bmi){const h=Number(bmi[1])/100,w=Number(bmi[2]),value=w/(h*h),category=value<18.5?'underweight':value<25?'in the healthy range':value<30?'overweight':'in the obesity range';return finish(`Your estimated BMI is ${value.toFixed(1)}, which is ${category}. A general healthy BMI range is 18.5–24.9. This is educational information, not a diagnosis.`,['Diet Plans','Workout Plans']);}
  if(q.includes('appointment')||q.includes('find doctor')||q.includes('need doctor')||q.includes('available doctor'))return finish('I can take you to available doctors and appointment booking.',['Book Appointment','Find Doctor']);
  if(q.includes('predict')||symptoms.some(term=>q.includes(term)))return finish(`I noticed symptom${symptoms.filter(term=>q.includes(term)).length>1?'s':''} in your message. How long have you had these symptoms, and are they getting worse? You can also run the UHS AI Disease Prediction with the symptoms already selected.`,['Predict Disease']);
  if(q.includes('paracetamol'))return finish('Paracetamol is commonly used for pain and fever. Follow the label or a clinician’s advice, avoid exceeding the stated dose, and check with a pharmacist if you have liver disease or use other medicines containing paracetamol. Common side effects are uncommon at normal doses. This is educational information only.',['Medicine Information']);
  if(q.includes('ibuprofen'))return finish('Ibuprofen can help with pain, inflammation, and fever. It may irritate the stomach and is not suitable for everyone, including some people with kidney disease, ulcers, or certain heart conditions. Ask a clinician or pharmacist about the right dose for you. This is educational information only.',['Medicine Information']);
  if(q.includes('amoxicillin'))return finish('Amoxicillin is a prescription antibiotic for specific bacterial infections. It does not treat viral colds or flu. Take it only when prescribed, and seek urgent advice for signs of an allergic reaction. This is educational information only.',['Medicine Information']);
  if(q.includes('diabetes'))return finish('Diabetes is a condition in which blood glucose remains too high because the body does not make enough insulin or cannot use it effectively. Healthy meals, regular activity, and clinician-guided monitoring can help.',['Health Articles','Diet Plans','Find Doctor']);
  if(q.includes('dengue'))return finish('Dengue can cause high fever, severe headache, body aches, rash, or nausea. Seek urgent care for warning signs such as severe abdominal pain, persistent vomiting, bleeding, or extreme weakness. Avoid self-medicating with ibuprofen or aspirin unless a clinician advises it.',['Find Doctor','Nearby Hospitals']);
  if(q.includes('diet')||q.includes('weight loss')||q.includes('weight gain')||q.includes('hypertension'))return finish('A sustainable plan focuses on vegetables, fruit, protein, whole grains, hydration, and portions suited to your needs. For diabetes or hypertension, personalised advice from a clinician or dietitian is especially helpful.',['Diet Plans','Find Doctor']);
  if(q.includes('workout')||q.includes('exercise'))return finish('For a beginner-friendly routine, start with 20–30 minutes of walking most days, two light strength sessions each week, and gentle mobility work. Increase gradually and stop if you feel pain, dizziness, or chest discomfort.',['Workout Plans']);
  if(q.includes('article')||q.includes('nutrition')||q.includes('heart disease'))return finish('I can take you to the UHS health library to browse clinically focused articles.',['Health Articles']);
  if(q.includes('report')||q.includes('prescription')||q.includes('medical history')||q.includes('dashboard')||q.includes('profile'))return finish('I can open your secure UHS health area.',['Medical Reports','View Prescriptions','My Appointments']);
  if(/movie|sport|politic|coding|math|weather|game/.test(q))return finish("I'm designed specifically to assist with healthcare services available through UHS. Please choose a healthcare option below.",allActions);
  return finish("I'm sorry, I couldn't understand that request. I can help with the healthcare options below.",allActions);
}

export function ChatAssistant(){
  const {user}=useAuth(),navigate=useNavigate(),location=useLocation(); const [open,setOpen]=useState(false),[input,setInput]=useState(''),[typing,setTyping]=useState(false);
  const [messages,setMessages]=useState<Message[]>([]); const endRef=useRef<HTMLDivElement>(null); const storageKey=user?`uhs_ai_chat_${user.id}`:'uhs_ai_chat_guest';
  useEffect(()=>{const initial=user?[greeting(user.firstName,user.role)]:[greeting()];try{setMessages(JSON.parse(sessionStorage.getItem(storageKey)??'null')??initial)}catch{setMessages(initial)}},[storageKey,user?.id]);
  useEffect(()=>{if(storageKey&&messages.length)sessionStorage.setItem(storageKey,JSON.stringify(messages));endRef.current?.scrollIntoView({behavior:'smooth'})},[messages,typing,storageKey]);
  const selectAction=(action:string)=>{if(protectedActions.has(action)&&!user){navigate('/login',{state:{from:location.pathname}});setOpen(false);return} if(action==='Predict Disease'){const latest=[...messages].reverse().find(message=>message.from==='user')?.text.toLowerCase()??'';const found=symptoms.filter(symptom=>latest.includes(symptom));navigate(`/predict${found.length?`?symptoms=${encodeURIComponent(found.join(','))}`:''}`);setOpen(false);return} const path=actionPath(action,user?.role);navigate(path);setOpen(false)};
  const send=async(event?:FormEvent)=>{event?.preventDefault();const value=input.trim();if(!value||typing)return;const userMessage:Message={id:Date.now(),from:'user',text:value};const history=messages.slice(-10).filter(message=>message.id!==messages[0]?.id).map(message=>({role:message.from==='assistant'?'model' as const:'user' as const,text:message.text}));setMessages(current=>[...current,userMessage]);setInput('');setTyping(true);try{const answer=await api<{text:string}>('/assistant/chat',{method:'POST',body:JSON.stringify({message:value,history})});const text=answer.text.includes('Is there anything else I can help you with?')?answer.text:`${answer.text}\n\nIs there anything else I can help you with?`;setMessages(current=>[...current,{id:Date.now(),from:'assistant',text,actions:['Book Appointment','Predict Disease','Find Doctor','Health Articles']}])}catch{setMessages(current=>[...current,replyFor(value)])}finally{setTyping(false)}};
  return <div className="uhs-chat"><button className="uhs-chat-launcher" onClick={()=>setOpen(value=>!value)} aria-label={open?'Close UHS AI Assistant':'Open UHS AI Assistant'}>{open?<X/>:<MessageCircle/>}<i/></button>{open&&<section className="uhs-chat-window" aria-label="UHS AI Assistant"><header><span><Bot/> UHS AI Assistant<small>Healthcare & platform support</small></span><button className="uhs-chat-close" onClick={()=>setOpen(false)} aria-label="Close chat"><X/></button></header><div className="uhs-chat-messages">{messages.map(message=><div className={`uhs-chat-message ${message.from}`} key={message.id}>{message.from==='assistant'&&<Bot/>}<div><p>{message.text}</p>{message.actions&&<div className="uhs-chat-chips">{message.actions.map(action=><button onClick={()=>selectAction(action)} key={action}>{action}</button>)}</div>}</div></div>)}{typing&&<div className="uhs-chat-message assistant"><Bot/><div className="uhs-typing"><i/><i/><i/></div></div>}<div ref={endRef}/></div><form onSubmit={send}><input value={input} onChange={event=>setInput(event.target.value)} placeholder="Ask about UHS or your health…" aria-label="Message UHS AI Assistant"/><button type="submit" disabled={!input.trim()||typing} aria-label="Send message"><Send/></button></form><footer><HeartPulse/> Educational guidance only — not a diagnosis or emergency care.</footer></section>}</div>
}
