import {useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,Star,MapPin,Clock} from 'lucide-react';
import type {Doctor,Hospital} from '../types';
export function Button({children,to,variant='primary',type='button',onClick,disabled}:{children:React.ReactNode;to?:string;variant?:'primary'|'secondary'|'ghost';type?:'button'|'submit';onClick?:()=>void;disabled?:boolean}){const cls=`btn btn-${variant}`;return to?<Link className={cls} to={to}>{children}</Link>:<button className={cls} type={type} onClick={onClick} disabled={disabled}>{children}</button>}
export function Avatar({src,name,className=''}:{src:string;name:string;className?:string}){const [failed,setFailed]=useState(false);const initials=name.replace('Dr. ','').split(' ').map(x=>x[0]).slice(0,2).join('');return failed||!src?<div role="img" aria-label={name} className={`avatar-fallback ${className}`}>{initials}</div>:<img className={className} src={src} alt={name} loading="lazy" onError={()=>setFailed(true)}/>}
export function SectionTitle({eyebrow,title,text,center=false}:{eyebrow:string;title:string;text?:string;center?:boolean}){return <div className={`section-title ${center?'center':''}`}><span>{eyebrow}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
export function DoctorCard({doctor}:{doctor:Doctor}){return <article className="doctor-card card"><div className="doctor-photo"><Avatar src={doctor.image} name={doctor.name}/><div className="rating"><Star size={14} fill="currentColor"/> {doctor.rating}</div></div><div className="doctor-body"><span className="pill">{doctor.specialty}</span><h3>{doctor.name}</h3><p>{doctor.hospital}</p><div className="doctor-meta"><span><Clock size={15}/>{doctor.experience} years</span><span className="available">● {doctor.available}</span></div><div className="card-actions"><Button to={`/doctors/${doctor.id}`} variant="secondary">View profile</Button><Button to={`/book?doctor=${doctor.id}`}>Book now</Button></div></div></article>}
export function HospitalCard({hospital}:{hospital:Hospital}){return <article className="hospital-card card"><img src={hospital.image} alt={hospital.name} loading="lazy"/><div><div className="row"><span className="pill">{hospital.emergency?'24/7 Emergency':'Clinic'}</span><span><Star size={14} fill="currentColor"/> {hospital.rating}</span></div><h3>{hospital.name}</h3><p><MapPin size={15}/>{hospital.location} · {hospital.distance}</p><div className="tags">{hospital.departments.map(x=><span key={x}>{x}</span>)}</div><Button to="/hospitals" variant="secondary">View details <ArrowRight size={16}/></Button></div></article>}
export function Stat({value,label}:{value:string;label:string}){return <div className="stat"><strong>{value}</strong><span>{label}</span></div>}
